### ISSUE TITLE
where is the notebook?

### ISSUE THREAD

**Issue by hasibzunair** [gm-spacagna/docem#1]

**Comment by h-joaomario** [comment]
Sorry I am still working on it before to upload it in github. Meanwhile you can read about here: https://towardsdatascience.com/extracting-rich-embedding-features-from-coco-pictures-using-pytorch-and-resnext-wsl-vademecum-of-6fdbdbe876a8 and follow the link at the bottom that will take you to the Colab dev notebook.

**Comment by gm-spacagna** [comment]
Sorry I am still working on it before to upload it in github. Meanwhile you can read about here: https://towardsdatascience.com/extracting-rich-embedding-features-from-coco-pictures-using-pytorch-and-resnext-wsl-vademecum-of-6fdbdbe876a8 and follow the link at the bottom that will take you to the Colab dev notebook.

**Comment by hasibzunair** [comment]
Alright! Thanks.

**Comment by gm-spacagna** [comment]
I have just uploaded the notebook and the links to Colab.
